# Generated by Django 5.2.6 on 2026-09-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_userregister_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
